# Generated by Django 5.2.6 on 2025-09-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='matricula',
        ),
    ]
