# Generated by Django 5.2.6 on 2025-09-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0002_colaborador_equipamento_usuario_emprestimo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='cliente',
            new_name='colaborador',
        ),
        migrations.RenameField(
            model_name='historico_emprestimo',
            old_name='aluguel',
            new_name='emprestimo',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('ativo', 'ativo'), ('em atraso', 'em atraso'), ('devolvido', 'devolvido')], default='ativo', max_length=20),
        ),
    ]
