# Generated by Django 5.2.6 on 2025-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0002_remove_colaborador_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimoequipamento',
            name='data_devolucao_prevista',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Devolução Prevista'),
        ),
        migrations.AddField(
            model_name='emprestimoequipamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
