# Generated by Django 5.2.6 on 2025-09-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0003_rename_cliente_emprestimo_colaborador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='produto',
            new_name='equipamento',
        ),
    ]
