# Generated by Django 5.2.6 on 2025-10-09 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0003_emprestimoequipamento_data_devolucao_prevista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimoequipamento',
            options={'ordering': ['-data_emprestimo'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AddField(
            model_name='emprestimoequipamento',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade Emprestada'),
        ),
        migrations.AlterField(
            model_name='emprestimoequipamento',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projeto_imersaos.colaborador'),
        ),
        migrations.AlterField(
            model_name='emprestimoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Projeto_imersaos.equipamento'),
        ),
    ]
