# Generated by Django 5.2.6 on 2025-09-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0004_rename_produto_emprestimo_equipamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='equipamento',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projeto_imersaos.colaborador'),
        ),
    ]
