# Generated by Django 5.2.6 on 2025-09-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0006_equipamentos_alter_emprestimo_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('em_atraso', 'Em Atraso'), ('devolvido', 'Devolvido')], default='ativo', max_length=20)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.RemoveField(
            model_name='historico_emprestimo',
            name='emprestimo',
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.RenameModel(
            old_name='Equipamentos',
            new_name='Equipamento',
        ),
        migrations.AddField(
            model_name='emprestimoequipamento',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='Projeto_imersaos.colaborador'),
        ),
        migrations.AddField(
            model_name='emprestimoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='Projeto_imersaos.equipamento'),
        ),
        migrations.DeleteModel(
            name='emprestimo',
        ),
        migrations.DeleteModel(
            name='historico_emprestimo',
        ),
    ]
