# Generated by Django 5.2.6 on 2025-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0007_emprestimoequipamento_delete_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='contato',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
