# Generated by Django 5.2.6 on 2025-09-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto_imersaos', '0008_remove_colaborador_contato_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimoequipamento',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projeto_imersaos.colaborador'),
        ),
        migrations.AlterField(
            model_name='emprestimoequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projeto_imersaos.equipamento'),
        ),
    ]
